language: android
before_install:
  # fix the 64bit box
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
  # download the latest android sdk and unzip
  - wget http://dl.google.com/android/android-sdk_r23.0.2-linux.tgz
  - tar -zxf android-sdk_r23.0.2-linux.tgz
  # setup your ANDROID_HOME and PATH environment variables
  # use ~/builds/[Github username]/[project]/android-sdk-linux
  - export ANDROID_HOME=`pwd`/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  # Download the android sdk we need
  # Android Platform tools, required to compile
  - TOOLS=$(android list sdk --no-ui | grep "Android SDK Platform-tools" | cut -d"-" -f1)
  - echo yes | android update sdk --filter "$TOOLS" --no-ui --force
  # API 16 stuff which needs to be provided
  - SDK=$(android list sdk --no-ui | grep ", API 16," | cut -d"-" -f1)
  - echo yes | android update sdk --filter "$SDK" --no-ui --force

android:
  components:
    - build-tools-19.0.2